#!/bin/sh
#
# Copyright (C) 2023 The Corpspace technologies.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
#

. "$(dirname "$0")/_/husky.sh"


npx --no-install lint-staged
